### ISSUE TITLE
Proposal: Establishing a Robust Methodology for Branching, Merging, and Committing Practices

### ISSUE THREAD

**Issue by ksachtleben** [DOJO-Smart-Ways/DOJO-Beam-Transforms#17]
## Overview
As our project grows in complexity and our team expands, the need for a clearly defined and robust methodology surrounding our use of Git branches, merges, and commits has become increasingly apparent. This proposal aims to initiate a discussion on developing a comprehensive strategy that outlines when, why, and what practices we should adopt to streamline our development process, improve collaboration, and maintain a high-quality codebase.

## Objectives
- **Enhance Collaboration:** Establish clear guidelines for using branches and merges to facilitate parallel development and reduce conflicts.
- **Improve Code Quality:** Define commit standards that ensure a clean and traceable history, making it easier to identify changes and troubleshoot issues.
- **Streamline Development Process:** Create a workflow that accommodates our project's scale and complexity, ensuring that features, fixes, and updates are integrated smoothly and efficiently.

### When to Branch
- Identifying scenarios that necessitate creating a new branch (e.g., new features, bug fixes, hotfixes).
- Guidelines for branch lifespan and when to merge back into the mainline.

### Why to Branch
- The rationale behind branching for parallel development, experimenting new ideas, and isolating changes.
- How branching can help in managing releases and supporting multiple versions of the product.

### What Branching Strategy to Adopt
- Evaluation of different branching strategies (e.g., Git Flow, GitHub Flow, GitLab Flow) to find the most suitable for our project needs.
- Considerations for branch naming conventions to maintain an organized and understandable branch structure.

### Commit Practices
- Establishing commit message standards that provide clarity on the changes made for future reference and documentation.
- Strategies for squashing commits and when it's appropriate to do so to maintain a clean history.

### Merging Best Practices
- Defining merge strategies (e.g., merge commit, squash merge, rebase) and when to use each for integrating changes.
- Criteria for code reviews and approvals before merges to ensure only high-quality code is added to the mainline.

## Next Steps
I propose we schedule a meeting to discuss these points in detail, allowing everyone to contribute their ideas and experiences. Following this, we can draft a document outlining our agreed-upon practices and integrate it into our project guidelines.

Your feedback and additional points for consideration are highly welcomed and will be crucial in shaping our approach to a more structured and efficient development process.

**Comment by gbsDojo** [comment]
**Response to Issue: Developing a Comprehensive Git Workflow Strategy**

Thank you for bringing up this crucial discussion. Given the practices we have already established, here are some additional insights and clarifications that can help shape our Git workflow strategy:

### Current Practices and Considerations

1. **Commit and Branch Naming Conventions**:
   - We are currently following the **Conventional Commits** specification for our commit messages, which helps in maintaining a clear and consistent commit history. This practice will be vital as we scale our project, making it easier to understand the context of changes and automate release notes.
   - For branch names, we are using a convention similar to our commit messages, such as `fix/add_columns`, `feature/new_add_columns`, and `refactor/add_column`. This naming strategy enhances clarity on the purpose and scope of the branch, aligning with our goal of organized and understandable branch structures.

2. **Versioning with Semantic Versioning (SemVer)**:
   - We have adopted Semantic Versioning (SemVer) for our project, which provides a clear framework for managing versions based on the nature of changes—whether they are major, minor, or patches. This practice is already integrated into our `setup.py` and will guide our release process moving forward.

3. **Merge Practices**:
   - Merges are currently handled exclusively through Pull Requests (PRs), which must pass our automated workflows. These workflows include unit tests, Docker image builds, and deployments to the Artifact Registry. Additionally, each PR requires approval from another team member, ensuring that only thoroughly reviewed and tested code is merged into the main branch.
   - This practice not only maintains code quality but also ensures that our CI/CD pipeline remains robust, with each merge being a reliable integration point.
